//array goes herequestArr = [
	(questObj1 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj2 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj3 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj4 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj5 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj6 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj7 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj8 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj9 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
	(questObj10 = {
		question: "some question",
		answer1: true,
		answer2: false,
		answer3: false,
		answer4: false,
	}),
];
